- platform: smartir
  name: MasterBedroom fan
  unique_id: bedroom_fan
  device_code: 1001
  controller_data:
    controller_type: Broadlink
    remote_entity: remote.ir_blaster_master_bedroom_remote
