# ESPresence One entry for each beacon you want to track
- platform: mqtt_room
  device_id: "known:6afe09508f42"
  state_topic: "espresense/devices/known:6afe09508f42"
  timeout: 10
  away_timeout: 120 # number of seconds after which the enitity will get status not_ho
- platform: sonarr_upcoming_media
  api_key: 193eebea1c39429494293b63ac6af2e1
  host: 192.168.1.103
  port: 8989
  days: 14
  ssl: true
  max: 10
